### ISSUE TITLE
AttributeError: 'Snake' object has no attribute 'turningDirection'

### ISSUE THREAD

**Issue by swojtczak** [grzjan5219/PythonGame#140]
Gra kraszuje sie po rozpoczeciu rozgrywki:
- kliknij start w menu -> na ekranie pojawia sie plansza
- NIE naciskaj spacji
- nacisnij kursory klawiatury -> gra się kraszuje. 

Mysle, ze wystarczy dolozyc atrybut turningDirection do klasy snake w inicjalizatorze.

**Comment by swojtczak** [comment]
ello from the pygame community. https://www.pygame.org/contribute.html
Traceback (most recent call last):
  File "C:\Praktyki\Gr2\PythonGame\menu.py", line 137, in <module>
    menu.intro()
  File "C:\Praktyki\Gr2\PythonGame\menu.py", line 96, in intro
    self.main_menu()
  File "C:\Praktyki\Gr2\PythonGame\menu.py", line 113, in main_menu
    game.Start()
  File "C:\Praktyki\Gr2\PythonGame\Game\game.py", line 85, in Start
    if self.snake.turningDirection == Direction.none:
AttributeError: 'Snake' object has no attribute 'turningDirection'
